/***************
CTAG TBD >>to be determined<< is an open source eurorack synthesizer module.

A project conceived within the Creative Technologies Arbeitsgruppe of
Kiel University of Applied Sciences: https://www.creative-technologies.de

(c) 2020 by Robert Manzke. All rights reserved.

The CTAG TBD software is licensed under the GNU General Public License
(GPL 3.0), available here: https://www.gnu.org/licenses/gpl-3.0.txt

The CTAG TBD hardware design is released under the Creative Commons
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).
Details here: https://creativecommons.org/licenses/by-nc-sa/4.0/

CTAG TBD is provided "as is" without any express or implied warranties.

License and copyright details for specific submodules are included in their
respective component folders / files if different from this license.
***************/


#include "ctagSoundProcessor.hpp"
#include <atomic>
#include <string>
#include <cmath>

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorSubSynth : public ctagSoundProcessor {
        public:
            void Process(const ProcessData &);

            ~ctagSoundProcessorSubSynth();

            ctagSoundProcessorSubSynth();

            const char *GetCStrID() const;

        private:
            void setParamValueInternal(const string &id, const string &key, const int val) override;

            void loadPresetInternal() override;

// autogenerated code here
// sectionHpp
const string id = "subsynth";
atomic<int32_t> ntype, trig_ntype;
atomic<int32_t> bwidth, cv_bwidth;
atomic<int32_t> nharms, cv_nharms;
atomic<int32_t> gain, cv_gain;
// sectionHpp


        };
    }
}