#include <atomic>
#include "ctagSoundProcessor.hpp"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorSimpleVCA : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;

            virtual ~ctagSoundProcessorSimpleVCA();

            ctagSoundProcessorSimpleVCA();

            virtual const char *GetCStrID() const override;

        private:
            void setParamValueInternal(const string &id, const string &key, const int val) override;
            void loadPresetInternal() override;

// autogenerated code here
// sectionHpp
const string id = "SimpleVCA";
void setIsStereo(){isStereo = false;}
atomic<int32_t> loudness, cv_loudness;
// sectionHpp


            // private attributes could go here

        };
    }
}