/***************
CTAG TBD >>to be determined<< is an open source eurorack synthesizer module.

A project conceived within the Creative Technologies Arbeitsgruppe of
Kiel University of Applied Sciences: https://www.creative-technologies.de

(c) 2020 by Robert Manzke. All rights reserved.

The CTAG TBD software is licensed under the GNU General Public License
(GPL 3.0), available here: https://www.gnu.org/licenses/gpl-3.0.txt

The CTAG TBD hardware design is released under the Creative Commons
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).
Details here: https://creativecommons.org/licenses/by-nc-sa/4.0/

CTAG TBD is provided "as is" without any express or implied warranties.

License and copyright details for specific submodules are included in their
respective component folders / files if different from this license.
***************/

#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "braids/analog_oscillator.h"
#include "braids/signature_waveshaper.h"
#include "braids/macro_oscillator.h"
#include "braids/settings.h"
#include "braids/quantizer.h"
#include "helpers/ctagADEnv.hpp"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorMacOsc : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;

           virtual void Init(std::size_t blockSize, void *blockPtr) override;

        private:

            virtual void knowYourself() override;

            // private attributes could go here
            braids::MacroOscillator osc;
            braids::SignatureWaveshaper ws;
            braids::Quantizer quantizer;
            CTAG::SP::HELPERS::ctagADEnv envelope;
            const uint8_t sync[32] = {0};
            bool prevTrigger = false;
            const uint16_t bit_reduction_masks[7] = {
                    0xc000,
                    0xe000,
                    0xf000,
                    0xf800,
                    0xff00,
                    0xfff0,
                    0xffff};

            // autogenerated code here
// sectionHpp
            atomic<int32_t> shape, cv_shape;
            atomic<int32_t> gain, cv_gain;
            atomic<int32_t> pitch, cv_pitch;
            atomic<int32_t> decimation, cv_decimation;
            atomic<int32_t> bit_reduction, cv_bit_reduction;
            atomic<int32_t> q_scale, cv_q_scale;
            atomic<int32_t> param_0, cv_param_0;
            atomic<int32_t> param_1, cv_param_1;
            atomic<int32_t> waveshaping, cv_waveshaping;
            atomic<int32_t> fm_amt, cv_fm_amt;
            atomic<int32_t> am_amt, cv_am_amt;
            atomic<int32_t> p0_amt, cv_p0_amt;
            atomic<int32_t> p1_amt, cv_p1_amt;
            atomic<int32_t> enableEG, trig_enableEG;
            atomic<int32_t> loopEG, trig_loopEG;
            atomic<int32_t> attack, cv_attack;
            atomic<int32_t> decay, cv_decay;
            // sectionHpp
        };
    }
}