/***************
CTAG TBD >>to be determined<< is an open source eurorack synthesizer module.

A project conceived within the Creative Technologies Arbeitsgruppe of
Kiel University of Applied Sciences: https://www.creative-technologies.de

(c) 2020 by Robert Manzke. All rights reserved.

The CTAG TBD software is licensed under the GNU General Public License
(GPL 3.0), available here: https://www.gnu.org/licenses/gpl-3.0.txt

The CTAG TBD hardware design is released under the Creative Commons
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).
Details here: https://creativecommons.org/licenses/by-nc-sa/4.0/

CTAG TBD is provided "as is" without any express or implied warranties.

License and copyright details for specific submodules are included in their
respective component folders / files if different from this license.
***************/

#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "mifx/oliverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorMIVerb2 : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;

            virtual ~ctagSoundProcessorMIVerb2();

           virtual void Init(std::size_t const &blockSize, void *const blockPtr) override;


        private:
            virtual void knowYourself() override;

            // private attributes could go here
            mifx::Oliverb reverb;
            float *reverb_buffer;

            // autogenerated code here
// sectionHpp
            atomic<int32_t> decay, cv_decay;
            atomic<int32_t> amount, cv_amount;
            atomic<int32_t> size, cv_size;
            atomic<int32_t> in_gain, cv_in_gain;
            atomic<int32_t> diffusion, cv_diffusion;
            atomic<int32_t> lp, cv_lp;
            atomic<int32_t> hp, cv_hp;
            atomic<int32_t> mod_amount, cv_mod_amount;
            atomic<int32_t> mod_rate, cv_mod_rate;
            atomic<int32_t> ratio, cv_ratio;
            atomic<int32_t> p_shift_amt, cv_p_shift_amt;
            // sectionHpp
        };
    }
}