/***************
CTAG TBD >>to be determined<< is an open source eurorack synthesizer module.

A project conceived within the Creative Technologies Arbeitsgruppe of
Kiel University of Applied Sciences: https://www.creative-technologies.de

(c) 2020 by Robert Manzke. All rights reserved.

The CTAG TBD software is licensed under the GNU General Public License
(GPL 3.0), available here: https://www.gnu.org/licenses/gpl-3.0.txt

The CTAG TBD hardware design is released under the Creative Commons
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).
Details here: https://creativecommons.org/licenses/by-nc-sa/4.0/

CTAG TBD is provided "as is" without any express or implied warranties.

License and copyright details for specific submodules are included in their
respective component folders / files if different from this license.
***************/

#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "mifx/reverb.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorMIVerb : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;

            virtual ~ctagSoundProcessorMIVerb();

            ctagSoundProcessorMIVerb();

            virtual const char *GetCStrID() const override;

        private:
            void setParamValueInternal(const string &id, const string &key, const int val) override;

            void loadPresetInternal() override;

// autogenerated code here
// sectionHpp
const string id = "MIVerb";
void setIsStereo(){isStereo = true;}
atomic<int32_t> time, cv_time;
atomic<int32_t> amount, cv_amount;
atomic<int32_t> in_gain, cv_in_gain;
atomic<int32_t> diffusion, cv_diffusion;
atomic<int32_t> lp, cv_lp;
atomic<int32_t> lfo1_f, cv_lfo1_f;
atomic<int32_t> lfo2_f, cv_lfo2_f;
// sectionHpp



            // private attributes could go here
            mifx::Reverb reverb;
            float *reverb_buffer;
        };
    }
}