#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "mifx/diffuser.h"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorMIDifu : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &);

            virtual ~ctagSoundProcessorMIDifu();

            ctagSoundProcessorMIDifu();

            virtual const char *GetCStrID() const;

        private:
            void setParamValueInternal(const string &id, const string &key, const int val) override;
            void loadPresetInternal() override;

// autogenerated code here
// sectionHpp
const string id = "MIDifu";
void setIsStereo(){isStereo = false;}
atomic<int32_t> amount, cv_amount;
atomic<int32_t> time, cv_time;
// sectionHpp



            // private attributes could go here
            mifx::Diffuser fx;
            float *fx_buffer;

        };
    }
}