#include <atomic>
#include "ctagSoundProcessor.hpp"

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorVoid : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
           virtual void Init(std::size_t const &blockSize, void *const blockPtr) override;
            virtual ~ctagSoundProcessorVoid();

        private:
            virtual void knowYourself() override;

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
	atomic<int32_t> dummy, trig_dummy;
	// sectionHpp
        };
    }
}