#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "helpers/ctagSineSource.hpp"
#include "helpers/ctagFastMath.hpp"
#include "helpers/ctagADEnv.hpp"            // Needed for AD EG (Attack/Decay Envelope Generator)
#include "helpers/ctagADSREnv.hpp"          // Needed for ADSR EG (Attack/Decay/Sustain/Release Envelope Generator)

#include "helpers/ctagWNoiseGen.hpp"
#include "helpers/ctagPNoiseGen.hpp"
#include "helpers/ctagFBDelayLine.hpp"
#include "mifx/reverb.h"

// --- VULT "Library for TBD" ---
#include "./vult/vult_formantor.h"
#include "./vult/vult_formantor.tables.h"

using namespace CTAG::SP::HELPERS;
namespace CTAG {
    namespace SP {
        class ctagSoundProcessorSpaceFX : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            ctagSoundProcessorSpaceFX();
            virtual ~ctagSoundProcessorSpaceFX();

        private:
            virtual void knowYourself() override;
		
            // --- Remember status of triggers / buttons ---
            inline int process_param_trig( const ProcessData &data, int trig_myparm, int my_parm, int prev_trig_state_id, int gate_type ); // rescale incoming data to bool
            enum trig_states
            {
                e_Trigger, e_Gate, e_ADenvNegative, e_ADtoSawLFOfrequ, e_ADSRtoSineLFOfrequ, e_ADSRenvNegative, e_ADegLoop, e_ADenvToVCA, e_ADSRenvToVCA,
                e_EnableNoise, e_SineEnable, e_PulseEnable, e_SawEnable, e_SquareEnable, e_SnH1Enable, e_SnH2Enable, e_EnableNoiseMod, e_ADenvEnable, e_ADSRenvEnable,
                e_ReverbEnable, e_ReverbIsMono, e_DelayEnable, e_DelayTimeShortened, e_VintageResonance, e_PitchToCutoff, e_SpaceFX_options_max
            };
            int prev_trig_state[e_SpaceFX_options_max] = {0};   // Initialize _all_ entries with "low value"
            bool low_reached[e_SpaceFX_options_max] = {false};  // We need this for look for toggle-events

            // --- Oscillators / LFOs ---
            ctagSineSource sine;
            ctagSineSource pulse;
            ctagSineSource lfoPWM;
            ctagSineSource square;

            ctagSineSource snh_sine_1;
            ctagSineSource snh_sine_2;

            // --- Noise inkl. modulation ---
            ctagWNoiseGen wNoise;
            ctagPNoiseGen pNoise;
            ctagSineSource noiseColourMod;
            ctagSineSource noiseLevelMod;

            ctagWNoiseGen snh_noise_1;
            ctagPNoiseGen snh_noise_2;

            // --- Envelopes ---
            ctagADEnv   eg_ad;
            ctagADSREnv eg_adsr;

            // --- Sample and Hold states and values ---
            bool snh_1_hold = false;
            bool snh_2_hold = false;
            float snh_1 = 0.f;
            float snh_2 = 0.f;

            // --- VULT Stuff ---
            Saw_eptr__ctx_type_0 saw_data;              // Saw oscillator data-structure
            Ladder__ctx_type_8 ladder_data;             // Ladder filter data-structure
            Ladder__ctx_type_6 ladder_vintage_data;     // Euler ladder algorithm

            // --- Delay ---
            const uint32_t maxDelayLength;
            const uint32_t shorterMaxDelayLength = maxDelayLength / 4;    // We have an option to shorten the delay-range for slapback delays
            HELPERS::ctagFBDelayLine dlyLine;
            float m_DelayTime = 0.f;          // Hysteresis values... (avoiding too abrupt changes...)
            float m_DelayFeedback = 0.f;

            // --- Mi Verb ---
            mifx::Reverb reverb;
            float *reverb_buffer;

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
	atomic<int32_t> Trigger, trig_Trigger;
	atomic<int32_t> MasterPitch, cv_MasterPitch;
	atomic<int32_t> MasterTune, cv_MasterTune;
	atomic<int32_t> FilterTracking, cv_FilterTracking;
	atomic<int32_t> Volume, cv_Volume;
	atomic<int32_t> EnableNoise, trig_EnableNoise;
	atomic<int32_t> NoiseColour, cv_NoiseColour;
	atomic<int32_t> MixedNoiseLevel, cv_MixedNoiseLevel;
	atomic<int32_t> EnableNoiseMod, trig_EnableNoiseMod;
	atomic<int32_t> NoiseColourModSpeed, cv_NoiseColourModSpeed;
	atomic<int32_t> NoiseColourModAmount, cv_NoiseColourModAmount;
	atomic<int32_t> NoiseLevelModSpeed, cv_NoiseLevelModSpeed;
	atomic<int32_t> NoiseLevelModAmount, cv_NoiseLevelModAmount;
	atomic<int32_t> PitchToCutoff, trig_PitchToCutoff;
	atomic<int32_t> Cutoff, cv_Cutoff;
	atomic<int32_t> Resonance, cv_Resonance;
	atomic<int32_t> VintageResonance, trig_VintageResonance;
	atomic<int32_t> CutoffModulationAmount, cv_CutoffModulationAmount;
	atomic<int32_t> ResonanceModulationAmount, cv_ResonanceModulationAmount;
	atomic<int32_t> AmplitudeModulationAmount, cv_AmplitudeModulationAmount;
	atomic<int32_t> ADenvEnable, trig_ADenvEnable;
	atomic<int32_t> ADenvToVCA, trig_ADenvToVCA;
	atomic<int32_t> ADattack, cv_ADattack;
	atomic<int32_t> ADdecay, cv_ADdecay;
	atomic<int32_t> ADegLoop, trig_ADegLoop;
	atomic<int32_t> ADenvNegative, trig_ADenvNegative;
	atomic<int32_t> ADenvelopeCutoffAmount, cv_ADenvelopeCutoffAmount;
	atomic<int32_t> ADenvelopeResonanceAmount, cv_ADenvelopeResonanceAmount;
	atomic<int32_t> ADtoSawLFOfrequ, trig_ADtoSawLFOfrequ;
	atomic<int32_t> ADtoSawSpeedLevel, cv_ADtoSawSpeedLevel;
	atomic<int32_t> ADSRenvEnable, trig_ADSRenvEnable;
	atomic<int32_t> ADSRenvToVCA, trig_ADSRenvToVCA;
	atomic<int32_t> ADSRattack, cv_ADSRattack;
	atomic<int32_t> ADSRdecay, cv_ADSRdecay;
	atomic<int32_t> ADSRsustain, cv_ADSRsustain;
	atomic<int32_t> ADSRrelease, cv_ADSRrelease;
	atomic<int32_t> ADSRenvNegative, trig_ADSRenvNegative;
	atomic<int32_t> ADSRenvelopeCutoffAmount, cv_ADSRenvelopeCutoffAmount;
	atomic<int32_t> ADSRenvelopeResonanceAmount, cv_ADSRenvelopeResonanceAmount;
	atomic<int32_t> ADSRtoSineLFOfrequ, trig_ADSRtoSineLFOfrequ;
	atomic<int32_t> ADSRtoSineSpeedLevel, cv_ADSRtoSineSpeedLevel;
	atomic<int32_t> SnH1Enable, trig_SnH1Enable;
	atomic<int32_t> SnH1Freq, cv_SnH1Freq;
	atomic<int32_t> SnH1CutoffLevel, cv_SnH1CutoffLevel;
	atomic<int32_t> SnH1ResonanceLevel, cv_SnH1ResonanceLevel;
	atomic<int32_t> SnH1AMlevel, cv_SnH1AMlevel;
	atomic<int32_t> SnH1FrequSnH2Change, cv_SnH1FrequSnH2Change;
	atomic<int32_t> SnH1FrequSquareChange, cv_SnH1FrequSquareChange;
	atomic<int32_t> SnH1ADattackChange, cv_SnH1ADattackChange;
	atomic<int32_t> SnH2Enable, trig_SnH2Enable;
	atomic<int32_t> SnH2Freq, cv_SnH2Freq;
	atomic<int32_t> SnH2CutoffLevel, cv_SnH2CutoffLevel;
	atomic<int32_t> SnH2ResonanceLevel, cv_SnH2ResonanceLevel;
	atomic<int32_t> SnH2AMlevel, cv_SnH2AMlevel;
	atomic<int32_t> SnH2FrequSnH1Change, cv_SnH2FrequSnH1Change;
	atomic<int32_t> SnH2FrequPulseChange, cv_SnH2FrequPulseChange;
	atomic<int32_t> SnH2ADdecayChange, cv_SnH2ADdecayChange;
	atomic<int32_t> SineEnable, trig_SineEnable;
	atomic<int32_t> SineFreq, cv_SineFreq;
	atomic<int32_t> SineCutoffAmount, cv_SineCutoffAmount;
	atomic<int32_t> SineResonanceAmount, cv_SineResonanceAmount;
	atomic<int32_t> SineAMamount, cv_SineAMamount;
	atomic<int32_t> PulseEnable, trig_PulseEnable;
	atomic<int32_t> PulseFreq, cv_PulseFreq;
	atomic<int32_t> PulseWidth, cv_PulseWidth;
	atomic<int32_t> PWMspeed, cv_PWMspeed;
	atomic<int32_t> PWMamount, cv_PWMamount;
	atomic<int32_t> PulseCutoffAmount, cv_PulseCutoffAmount;
	atomic<int32_t> PulseResonanceAmount, cv_PulseResonanceAmount;
	atomic<int32_t> PulseAMamount, cv_PulseAMamount;
	atomic<int32_t> SawEnable, trig_SawEnable;
	atomic<int32_t> SawFreq, cv_SawFreq;
	atomic<int32_t> SawCutoffAmount, cv_SawCutoffAmount;
	atomic<int32_t> SawResonanceAmount, cv_SawResonanceAmount;
	atomic<int32_t> SawAMamount, cv_SawAMamount;
	atomic<int32_t> SquareEnable, trig_SquareEnable;
	atomic<int32_t> SquareFreq, cv_SquareFreq;
	atomic<int32_t> SquareCutoffAmount, cv_SquareCutoffAmount;
	atomic<int32_t> SquareResonanceAmount, cv_SquareResonanceAmount;
	atomic<int32_t> SquareAMamount, cv_SquareAMamount;
	atomic<int32_t> DelayEnable, trig_DelayEnable;
	atomic<int32_t> DelayTimeShortened, trig_DelayTimeShortened;
	atomic<int32_t> DelayTime, cv_DelayTime;
	atomic<int32_t> DelayFeedback, cv_DelayFeedback;
	atomic<int32_t> DelayDryWet, cv_DelayDryWet;
	atomic<int32_t> ReverbEnable, trig_ReverbEnable;
	atomic<int32_t> ReverbIsMono, trig_ReverbIsMono;
	atomic<int32_t> RevInputGain, cv_RevInputGain;
	atomic<int32_t> RevDiffusion, cv_RevDiffusion;
	atomic<int32_t> RevTime, cv_RevTime;
	atomic<int32_t> RevLowpass, cv_RevLowpass;
	atomic<int32_t> RevLFO1, cv_RevLFO1;
	atomic<int32_t> RevLFO2, cv_RevLFO2;
	atomic<int32_t> RevAmount, cv_RevAmount;
	// sectionHpp
        };
    }
}