#include <atomic>
#include "ctagSoundProcessor.hpp"
#include "airwindows/EveryTrim.hpp"


namespace CTAG {
    namespace SP {
        class ctagSoundProcessorEveryTrim : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
            ctagSoundProcessorEveryTrim();
            virtual ~ctagSoundProcessorEveryTrim();

        private:
            virtual void knowYourself() override;

            airwindows::EveryTrim everytrim;

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
	atomic<int32_t> left, cv_left;
	atomic<int32_t> right, cv_right;
	atomic<int32_t> mid, cv_mid;
	atomic<int32_t> side, cv_side;
	atomic<int32_t> master, cv_master;
	// sectionHpp
        };
    }
}