image:
  file: .gitpod.Dockerfile
tasks:
 - name: Setup environment variables for ESP-IDF
   command: |
     source /home/gitpod/.espressif/frameworks/esp-idf/export.sh > /dev/null 2>&1
vscode:
  extensions:
    - espressif.esp-idf-extension
    - anwar.resourcemonitor
    - yzhang.markdown-all-in-one