#include <atomic>
#include <tbd/sound_processor.hpp>

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorVoid : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;
           virtual void Init(std::size_t blockSize, void *blockPtr) override;
            virtual ~ctagSoundProcessorVoid();

        private:
            virtual void knowYourself() override;

            // private attributes could go here
            // autogenerated code here
            // sectionHpp
	        std::atomic<int32_t> dummy, trig_dummy;
	        // sectionHpp
        };
    }
}