#include <atomic>
#include <tbd/sound_processor.hpp>
#include "helpers/ctagADEnv.hpp"
#include "braids/svf.h"

using namespace CTAG::SP::HELPERS;

namespace CTAG {
    namespace SP {
        class ctagSoundProcessorMISVF : public ctagSoundProcessor {
        public:
            virtual void Process(const ProcessData &) override;

           virtual void Init(std::size_t blockSize, void *blockPtr) override;

        private:
            virtual void knowYourself() override;

            // private attributes could go here
            ctagADEnv adEnv;
            int prevTrigState = 1;
            braids::Svf svf;
            // autogenerated code here
// sectionHpp
           std::atomic<int32_t> flt_mode, cv_flt_mode;
           std::atomic<int32_t> gain, cv_gain;
           std::atomic<int32_t> cutoff, cv_cutoff;
           std::atomic<int32_t> resonance, cv_resonance;
           std::atomic<int32_t> fm_amt, cv_fm_amt;
           std::atomic<int32_t> enableEG, trig_enableEG;
           std::atomic<int32_t> loopEG, trig_loopEG;
           std::atomic<int32_t> attack, cv_attack;
           std::atomic<int32_t> decay, cv_decay;
            // sectionHpp
        };
    }
}