/***************
CTAG TBD >>to be determined<< is an open source eurorack synthesizer module.

A project conceived within the Creative Technologies Arbeitsgruppe of
Kiel University of Applied Sciences: https://www.creative-technologies.de

(c) 2020 by Robert Manzke. All rights reserved.

The CTAG TBD software is licensed under the GNU General Public License
(GPL 3.0), available here: https://www.gnu.org/licenses/gpl-3.0.txt

The CTAG TBD hardware design is released under the Creative Commons
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).
Details here: https://creativecommons.org/licenses/by-nc-sa/4.0/

CTAG TBD is provided "as is" without any express or implied warranties.

License and copyright details for specific submodules are included in their
respective component folders / files if different from this license.
***************/

#include <atomic>
#include <tbd/sound_processor.hpp>
#include "mifx/reverb.h"

namespace tbd::sounds {

struct SoundProcessorMIVerb : sound_processor::SoundProcessor {

    virtual void Process(const sound_processor::ProcessData&) override;

    ~SoundProcessorMIVerb();

    virtual void Init(std::size_t blockSize, void *blockPtr) override;

protected:

    // private attributes could go here
    mifx::Reverb reverb;
    float *reverb_buffer;

    // autogenerated code here
// sectionHpp
    std::atomic<int32_t> time, cv_time;
    std::atomic<int32_t> amount, cv_amount;
    std::atomic<int32_t> in_gain, cv_in_gain;
    std::atomic<int32_t> diffusion, cv_diffusion;
    std::atomic<int32_t> lp, cv_lp;
    std::atomic<int32_t> lfo1_f, cv_lfo1_f;
    std::atomic<int32_t> lfo2_f, cv_lfo2_f;
    // sectionHpp
};

}
