/***************
CTAG TBD >>to be determined<< is an open source eurorack synthesizer module.

A project conceived within the Creative Technologies Arbeitsgruppe of
Kiel University of Applied Sciences: https://www.creative-technologies.de

(c) 2020 by Robert Manzke. All rights reserved.

The CTAG TBD software is licensed under the GNU General Public License
(GPL 3.0), available here: https://www.gnu.org/licenses/gpl-3.0.txt

The CTAG TBD hardware design is released under the Creative Commons
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).
Details here: https://creativecommons.org/licenses/by-nc-sa/4.0/

CTAG TBD is provided "as is" without any express or implied warranties.

License and copyright details for specific submodules are included in their
respective component folders / files if different from this license.
***************/

#include <atomic>
#include <tbd/sound_processor.hpp>
#include "braids/analog_oscillator.h"
#include "braids/signature_waveshaper.h"
#include "braids/macro_oscillator.h"
#include "braids/settings.h"
#include "braids/quantizer.h"
#include <tbd/sound_utils/ctagADEnv.hpp>

namespace tbd::sounds {

struct SoundProcessorMacOsc : audio::SoundProcessor {

    virtual void Process(const audio::ProcessData&) override;
    virtual void Init(std::size_t blockSize, void *blockPtr) override;

protected:

    // private attributes could go here
    braids::MacroOscillator osc;
    braids::SignatureWaveshaper ws;
    braids::Quantizer quantizer;
    tbd::sound_utils::ctagADEnv envelope;
    const uint8_t sync[32] = {0};
    bool prevTrigger = false;
    const uint16_t bit_reduction_masks[7] = {
            0xc000,
            0xe000,
            0xf000,
            0xf800,
            0xff00,
            0xfff0,
            0xffff};

    // autogenerated code here
// sectionHpp
    std::atomic<int32_t> shape, cv_shape;
    std::atomic<int32_t> gain, cv_gain;
    std::atomic<int32_t> pitch, cv_pitch;
    std::atomic<int32_t> decimation, cv_decimation;
    std::atomic<int32_t> bit_reduction, cv_bit_reduction;
    std::atomic<int32_t> q_scale, cv_q_scale;
    std::atomic<int32_t> param_0, cv_param_0;
    std::atomic<int32_t> param_1, cv_param_1;
    std::atomic<int32_t> waveshaping, cv_waveshaping;
    std::atomic<int32_t> fm_amt, cv_fm_amt;
    std::atomic<int32_t> am_amt, cv_am_amt;
    std::atomic<int32_t> p0_amt, cv_p0_amt;
    std::atomic<int32_t> p1_amt, cv_p1_amt;
    std::atomic<int32_t> enableEG, trig_enableEG;
    std::atomic<int32_t> loopEG, trig_loopEG;
    std::atomic<int32_t> attack, cv_attack;
    std::atomic<int32_t> decay, cv_decay;
    // sectionHpp
};

}
