/***************
CTAG TBD >>to be determined<< is an open source eurorack synthesizer module.

A project conceived within the Creative Technologies Arbeitsgruppe of
Kiel University of Applied Sciences: https://www.creative-technologies.de

(c) 2020 by Robert Manzke. All rights reserved.

The CTAG TBD software is licensed under the GNU General Public License
(GPL 3.0), available here: https://www.gnu.org/licenses/gpl-3.0.txt

The CTAG TBD hardware design is released under the Creative Commons
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0).
Details here: https://creativecommons.org/licenses/by-nc-sa/4.0/

CTAG TBD is provided "as is" without any express or implied warranties.

License and copyright details for specific submodules are included in their
respective component folders / files if different from this license.
***************/

#include <atomic>
#include <tbd/sound_processor.hpp>
#include "airwindows/TDelay.hpp"

namespace tbd::sounds {
    
struct SoundProcessorTDelay : sound_processor::SoundProcessor {

    virtual void Process(const sound_processor::ProcessData&) override;
    virtual void Init(std::size_t blockSize, void *blockPtr) override;
    virtual ~SoundProcessorTDelay();

protected:
    airwindows::TDelay tdelay;
    float preDelay = 0.f;
    float preDepth = 0.f;
    float preLNFT = 0.f;
    // private attributes could go here
    // autogenerated code here
    // sectionHpp
    std::atomic<int32_t> bypass, trig_bypass;
    std::atomic<int32_t> depth, cv_depth;
    std::atomic<int32_t> delay, cv_delay;
    std::atomic<int32_t> feedback, cv_feedback;
    std::atomic<int32_t> lnft, cv_lnft;
    std::atomic<int32_t> dry, cv_dry;
    std::atomic<int32_t> wet, cv_wet;
    // sectionHpp
};

}
