esphome:
  name: tbdbba1
    
esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1
  framework: 
    type: esp-idf

external_components:
  - source: ${TBD_ROOT}/components/core
  - source: ${TBD_ROOT}/components/audio

tbd_es8388:
  pins:
    i2c:
      sda: 41
      scl: 20
    i2s:
      mclk: 39
      bclk: 45
      ws: 1
      dout: 2
      din: 21


tbd_config:



# tbd_codec:
#   type: 

# tbd_sound_processor: