esphome:
    name: tbddesktop

host:
  mac_address: "06:35:69:ab:f6:79"

external_components:
  - source: ${TBD_ROOT}
#  - source: /home/mlee/code/tbd_example/components

tbd_module:



tbd_sound_processor:

tbd_audio:
  autostart: true

tbd_test_plugins:

tbd_basic_sounds:
  whitelist:
    - void

tbd_rt_audio:

tbd_rt_midi:

tbd_api:

tbd_websocket:

uart:
  id: host_uart
  baud_rate: 9600
  port: "/dev/ttyUSB0"

tbd_uart:
  uart_id: host_uart

tbd_unittests:
