function(tbd_set_define define value)
    add_compile_definitions(${define}=${value})
    if (TBD_TOOLCHAIN STREQUAL "idf")
        idf_build_set_property(COMPILE_DEFINITIONS -D${define}=${value} APPEND)
    else()
    endif()
endfunction()

function(tbd_set_param var value)
    set(${var} ${value} CACHE STRING "" FORCE)
    mark_as_advanced(${var})
    if (TBD_TOOLCHAIN STREQUAL "idf")
        idf_build_set_property(${var} ${value})
    else()
    endif()
endfunction()
