from pathlib import Path
from typing import Final, Iterator

import proto_schema_parser.ast as proto
import proto_schema_parser.generator as protog

from tbd_core.buildgen import get_tbd_components_root
from tbd_core.generators import GeneratorBase, jilter
from tbd_core.reflection.db import ReflectableDB, ClassPtr, flattened_properties, PropertyPtr
from . import serializables
from .registry import Serializables

HEADER_NOTE = \
    """/** 
     * @warning: DO NOT EDIT!
     * 
     * This file was auto-generated by the TBD serialization library and will be overwritten!
     */
    """


class CppFilters:
    def __init__(self, reflectable_db: ReflectableDB):
        self._reflectable_db: Final[ReflectableDB] = reflectable_db

    @jilter
    def field_name(self, property_id: int) -> str:
        return self._reflectable_db.get_property(property_id).field_name

    @jilter
    def snake_name(self, path: str) -> str:
        return path.replace('.', '_')

    @jilter
    def flattened_properties(self, serializable: ClassPtr) -> Iterator[tuple[str, PropertyPtr]]:
        for path, prop in flattened_properties(serializable):
            yield '.'.join(path), prop


class SerializableGenerator(GeneratorBase[CppFilters]):
    def __init__(self, serializables: Serializables, reflectable_db: ReflectableDB):
        super().__init__(get_tbd_components_root() / 'core' / 'tbd_serialization' / 'src', CppFilters(reflectable_db))
        self._serializables: Serializables = serializables
        self._reflectable_db: ReflectableDB = reflectable_db

    def render(self, template_file: Path | str, **args) -> str:
        return super().render(template_file, reflectables=self._reflectable_db, **args)

    def write_cpp_code(self, domain: str, headers_dir: Path, srcs_dir: Path) -> None:
        cls_headers = {*[str(serializable.header.file) for serializable in self._serializables.serializable_classes],
                       *[str(serializable.header.file) for serializable in self._serializables.class_dtos]}

        dtos_header = self.render(
            'domain_dtos.hpp.j2',
            serializables=self._serializables,
            domain=domain,
            cls_headers=cls_headers)

        dtos_header_file = headers_dir / 'dtos.hpp'
        with open(dtos_header_file, 'w') as f:
            f.write(HEADER_NOTE)
            f.write(dtos_header)

        streams_header = self.render(
            'domain_serializables.hpp.j2',
            serializables=self._serializables,
            domain=domain,
            cls_headers=cls_headers
        )

        streams_header_file = headers_dir / 'serializables.hpp'
        with open(streams_header_file, 'w') as f:
            f.write(HEADER_NOTE)
            f.write(streams_header)

        streams_source = self.render(
            'domain_serializables.cpp.j2',
            serializables=self._serializables,
            domain=domain,
            cls_headers=cls_headers
        )
        streams_source_file = srcs_dir / f'serializables.cpp'
        with open(streams_source_file, 'w') as f:
            f.write(HEADER_NOTE)
            f.write(streams_source)

        messages_header = self.render(
            'domain_messages.hpp.j2',
            serializables=self._serializables,
            domain=domain,
            cls_headers=cls_headers,

        )
        messages_header_file = headers_dir / f'messages.hpp'
        with open(messages_header_file, 'w') as f:
            f.write(HEADER_NOTE)
            f.write(messages_header)

        messages_source = self.render(
            'domain_messages.cpp.j2',
            serializables=self._serializables,
            domain=domain,
            cls_headers=cls_headers)
        messages_source_file = srcs_dir / f'messages.cpp'
        with open(messages_source_file, 'w') as f:
            f.write(HEADER_NOTE)
            f.write(messages_source)


    def write_protos(self, out_file: Path) -> None:
        with out_file.open('w') as f:
            messages = protog.Generator().generate(proto.File(
                syntax='proto3',
                file_elements=list(self._serializables.messages.values()),
            ))
            f.writelines(messages)
