#include "ctagSoundProcessorTemplate.hpp"

using namespace CTAG::SP;

void ctagSoundProcessorTemplate::Process(const ProcessData &data) {
}

ctagSoundProcessorTemplate::ctagSoundProcessorTemplate() {
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);
}

ctagSoundProcessorTemplate::~ctagSoundProcessorTemplate() {
}

void ctagSoundProcessorTemplate::knowYourself(){
    // autogenerated code here
    // sectionCpp0
    // sectionCpp0
}