#include "ctagSoundProcessorTemplate.hpp"

using namespace CTAG::SP;

void ctagSoundProcessorTemplate::Process(const ProcessData &data) {
}

void ctagSoundProcessorTemplate::Init() {
    // construct internal data model
    knowYourself();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    LoadPreset(0);
}

// no ctor, use Init() instead, is called from factory after successful creation
// dtor
ctagSoundProcessorTemplate::~ctagSoundProcessorTemplate() {
}

void ctagSoundProcessorTemplate::knowYourself(){
    // autogenerated code here
    // sectionCpp0
    // sectionCpp0
}