#include "ctagSoundProcessorTemplate.hpp"
#include <iostream>

using namespace CTAG::SP;

ctagSoundProcessorTemplate::ctagSoundProcessorTemplate() {
    setIsStereo();
    model = std::make_unique<ctagSPDataModel>(id, isStereo);
    model->LoadPreset(0);
}

void ctagSoundProcessorTemplate::Process(const ProcessData &data) {
}

ctagSoundProcessorTemplate::~ctagSoundProcessorTemplate() {
}

const char *ctagSoundProcessorTemplate::GetCStrID() const {
    return id.c_str();
}


void ctagSoundProcessorTemplate::setParamValueInternal(const string& id, const string& key, const int val) {
// autogenerated code here
// sectionCpp0
// sectionCpp0
}

void ctagSoundProcessorTemplate::loadPresetInternal() {
// autogenerated code here
// sectionCpp1
// sectionCpp1
}
