POST http://ctag-tbd.local/api/v1/favorites/getAll
Accept: application/json
###
POST http://ctag-tbd.local/api/v1/favorites/getAll
Accept: application/json
###
POST http://ctag-tbd.local/api/v1/favorites/getAll
Accept: application/json
###
POST http://ctag-tbd.local/api/v1/favorites/getAll
Accept: application/json
###
POST http://ctag-tbd.local/api/v1/favorites/getAll
Accept: application/json
###
POST http://ctag-tbd.local/api/v1/favorites/store/0
Content-Type: application/json

{
 "name": "New Favorite",
 "plug_0": "Void",
 "pre_0": 0,
 "plug_1": "Void",
 "pre_1": 0,
 "ustring": "cool"
}
###
POST http://ctag-tbd.local/api/v1/favorites/store/1
Content-Type: application/json

{
 "name": "New Favorite",
 "plug_0": "Void",
 "pre_0": 0,
 "plug_1": "Void",
 "pre_1": 0,
 "ustring": "cool"
}
###
POST http://ctag-tbd.local/api/v1/favorites/store/2
Content-Type: application/json

{
 "name": "New Favorite",
 "plug_0": "Void",
 "pre_0": 0,
 "plug_1": "Void",
 "pre_1": 0,
 "ustring": "cool"
}
###
POST http://ctag-tbd.local/api/v1/favorites/store/3
Content-Type: application/json

{
 "name": "New Favorite",
 "plug_0": "Void",
 "pre_0": 0,
 "plug_1": "Void",
 "pre_1": 0,
 "ustring": "cool"
}
###
POST http://ctag-tbd.local/api/v1/favorites/store/4
Content-Type: application/json

{
 "name": "New Favorite",
 "plug_0": "Void",
 "pre_0": 0,
 "plug_1": "Void",
 "pre_1": 0,
 "ustring": "cool"
}
###
POST http://ctag-tbd.local/api/v1/favorites/recall/0
Accept: application/json
###
POST http://ctag-tbd.local/api/v1/favorites/recall/1
Accept: application/json
###
POST http://ctag-tbd.local/api/v1/favorites/recall/2
Accept: application/json
###
POST http://ctag-tbd.local/api/v1/favorites/recall/3
Accept: application/json
###
POST http://ctag-tbd.local/api/v1/favorites/recall/4
Accept: application/json
###
POST http://ctag-tbd.local/api/v1/favorites/recall/5
Accept: application/json
###