GET http://ctag-tbd.local/api/v1/getConfiguration
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/getConfiguration
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/getConfiguration
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/getConfiguration
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/getConfiguration
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/getConfiguration
Accept: application/json
###