GET http://ctag-tbd.local/api/v1/getPresetData/Subbotnik
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/getPresetData/Void
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/getPresetData/Void
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/getPresetData/Void
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/getPresetData/Void
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/getPresetData/Void
Accept: application/json
###