GET http://ctag-tbd.local/api/v1/loadPreset/0?number=0
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/loadPreset/0?number=0
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/loadPreset/0?number=0
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/loadPreset/0?number=0
Accept: application/json
###

