GET http://ctag-tbd.local/api/v1/savePreset/0?number=0&name=coolname
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/savePreset/0?number=0&name=coolname
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/savePreset/0?number=0&name=coolname
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/savePreset/0?number=0&name=coolname
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/savePreset/0?number=0&name=coolname
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/savePreset/1?number=0&name=coolname
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/savePreset/1?number=0&name=coolname
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/savePreset/1?number=0&name=coolname
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/savePreset/1?number=0&name=coolname
Accept: application/json
###
GET http://ctag-tbd.local/api/v1/savePreset/1?number=0&name=coolname
Accept: application/json
###