name: cloud-compiler

on:
  workflow_dispatch:
    inputs:
      apps:
        description: 'Apps to be removed from tbd.'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Echo removed apps
      run: |
        echo "${{ github.event.inputs.apps }}" > python .github/remove-apps.py
