name: cloud-compiler

on:
  workflow_dispatch:
    inputs:
      apps:
        description: 'Apps to be removed from tbd.'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Remove apps
      run: |
        echo "${{ github.event.inputs.apps }}" | python .github/remove-apps.py

    - name: Build binaries
      uses: ctag-fh-kiel/esp-idf-action@1

    - name: Update partition table and rom config
      run: |
        python .github/update-partition-table.py

    - name: Print partition table
      run: |
        cat partitions_example.csv

    - name: Build binaries
      uses: ctag-fh-kiel/esp-idf-action@1

    - name: Archive binaries
      run: |
        zip --junk-paths binaries build/*.bin build/bootloader/*.bin build/partition_table/*.bin

    - name: Upload binary
      uses: actions/upload-artifact@v2.2.1
      with:
        name: Custom tbd firmware
        # A file, directory or wildcard pattern that describes what to upload
        path: ./binaries.zip
